# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false
before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
    warnings_are_errors: false