# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache: packages
latex: false

apt_packages:
  - libgsl-dev
  
brew_packages: 
  - gsl
 
jobs:
  include:
  - r: devel
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
    warnings_are_errors: false